### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by abhishek77in** [solidusio/solidus_multi_domain#28]
> Code without an explicit license is protected by copyright and is by default All Rights Reserved. The person or people who wrote the code are protected as such. Any time you're using software you didn't write, licensing should be considered and abided.

We would like to make use of this gem. It would be very useful to have `LICENSE.md` file which clarifies in what manner the gem can be used. 

Site which one can use to decide which licence to use - http://choosealicense.com/

**Comment by adammathys** [comment]
Thanks for pointing this out, I've opened #35 to remedy this.
