### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by ajkamel** [solidusio/solidus_multi_domain#33]
When using the store edit view there is a missing translation error for `back_to_stores_list:` and `yes:`  I manually added these to my en.yml file however it only picks up the back to stores key and not the yes key.

Missing Translations in core: 

- [ ] en.spree.back_to_stores_list:
- [ ] en.spree.yes
- [ ] en.spree.no
- [ ] en.store

**Comment by ajkamel** [comment]
yes needs to be overridden as yml files have certain reserved words such as yes and no as seen here

http://yaml.org/type/bool.html

**Comment by adammathys** [comment]
Thanks for pointing theses out, I just noticed them myself. I'll toss together a PR to clean up the missing translations.
