### ISSUE TITLE
Spree::Tracker.current looks for store code instead of store id

### ISSUE THREAD

**Issue by ajkamel** [solidusio/solidus_multi_domain#34]
@jhawthorn  Just a quick question.  Since Spree Front-End uses [`Spree:Tracker.current`](https://github.com/solidusio/solidus/blob/master/frontend/app/views/spree/shared/_google_analytics.html.erb#L1) with no variable being passed in do we want to allow it to change this to check the store id in the session?  Also would it make sense to have [`Tracker.current decorator`](https://github.com/solidusio/solidus_multi_domain/blob/master/app/models/spree/tracker_decorator.rb#L5 ) check for the `params[:current_store_id]` rather than the store code or url?

**Comment by dholdren** [comment]
@ajkamel check out https://github.com/solidusio/solidus_multi_domain/pull/41
I think it resolves this issue.

**Comment by adammathys** [comment]
Fixed by #41.
