### ISSUE TITLE
Error by installing

### ISSUE THREAD

**Issue by servisof** [solidusio/solidus_multi_domain#59]
When installing with "rails g solidus_multi_domain:install" after successful "bundle install", I got the error "uninitialized constant Spree::Tracker (NameError)". The output is: 
$ rails g solidus_multi_domain:install
/home/carlos/.rvm/gems/ruby-2.3.1/gems/solidus_multi_domain-1.5.0/app/models/spree/tracker_decorator.rb:1:in `<top (required)>': uninitialized constant Spree::Tracker (NameError) from /home/carlos/.rvm/gems/ruby-2.3.1/gems/solidus_multi_domain-1.5.0/lib/spree_multi_domain/engine.rb:11:in `block (2 levels) in activate'
	from /home/carlos/.rvm/gems/ruby-2.3.1/gems/solidus_multi_domain-1.5.0/lib/spree_multi_domain/engine.rb:10:in `glob'
	from /home/carlos/.rvm/gems/ruby-2.3.1/gems/solidus_multi_domain-1.5.0/lib/spree_multi_domain/engine.rb:10:in `block in activate'
	from /home/carlos/.rvm/gems/ruby-2.3.1/gems/solidus_multi_domain-1.5.0/lib/spree_multi_domain/engine.rb:9:in `each'
...
Help please !!!

**Comment by servisof** [comment]
I'ḿ using ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux] with Rails 5.0.0.1.

**Comment by adammathys** [comment]
The master version of Solidus moved trackers to an extension: https://github.com/solidusio-contrib/solidus_trackers

Adding that dependency to your Gemfile should fix this error. I'll make a note of this in the README until we can come up with a better solution.

**Comment by servisof** [comment]
That dependency solved the error above... Thanks you.
