### ISSUE TITLE
Available for 2.1 solidus version?

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus_multi_domain#61]
I have seen that it is for solidus versions under 2. isn't it?

**Comment by adammathys** [comment]
The tests are currently running against Solidus v2.1 without any issue, so it should work. If there are any issues, bug reports would very much be welcome.

http://extensions.solidus.io/

**Comment by sechix** [comment]
Perfect, I finally could install, It was due to I was in 2.2 solidus version, in 2.1 works, thanks a lot!!!!
